# Generated Terraform Configuration
# Resource: aws_s3_bucket.cloudfront_logs_bucket
# Generated by PACE InfraFlow Manager

resource "aws_s3_bucket" "cloudfront_logs_bucket" {
  bucket              = "amazon-cloudfront-secure-static-site-s3bucketlogs-yq5t0b34xw7i"
  force_destroy       = false
  object_lock_enabled = false
  region              = "us-east-1"
  tags = {
    Solution = "ACFS3"
  }
}