# Generated Terraform Configuration
# Resource: aws_s3_bucket.cloudfront_root_bucket
# Generated by PACE InfraFlow Manager

resource "aws_s3_bucket" "cloudfront_root_bucket" {
  bucket              = "amazon-cloudfront-secure-static-site-s3bucketroot-camuye2j1m5u"
  force_destroy       = false
  object_lock_enabled = false
  region              = "us-east-1"
  tags = {
    Solution = "ACFS3"
  }
}