# Generated Terraform Configuration
# Resource: aws_eks_cluster.edgeopshelmcluster
# Generated by PACE InfraFlow Manager

resource "aws_eks_cluster" "edgeopshelmcluster" {
  bootstrap_self_managed_addons = false
  deletion_protection           = false
  enabled_cluster_log_types     = []
  force_update_version          = null
  name                          = "Edgeopshelmcluster"
  region                        = "us-east-1"
  role_arn                      = "arn:aws:iam::682452625784:role/Ekshelmrole"
  tags = {
    Owner   = "PACE_hydra@ust.com"
    mcm-app = "d337063fa50c487ca51c26a02df15ef3"
    mcm-d   = "7ea2ad33908c422eae4d52f878207300"
    mcm-env = "8dd2f8baf71d4acbb9f598eff9092393"
    mcm-p   = "a9555a6962b74194baf95190a9fd6dbf"
    project = "DAgility"
  }
  version = "1.33"
  access_config {
    authentication_mode                         = "CONFIG_MAP"
    bootstrap_cluster_creator_admin_permissions = true
  }
  control_plane_scaling_config {
    tier = "standard"
  }
  kubernetes_network_config {
    ip_family         = "ipv4"
    service_ipv4_cidr = "10.100.0.0/16"
    elastic_load_balancing {
      enabled = false
    }
  }
  upgrade_policy {
    support_type = "EXTENDED"
  }
  vpc_config {
    endpoint_private_access = true
    endpoint_public_access  = true
    public_access_cidrs     = ["35.172.2.201/32", "52.1.62.207/32", "54.167.139.34/32"]
    security_group_ids      = ["sg-095178f5a628985c9"]
    subnet_ids              = ["subnet-00fa03bc15525e15c", "subnet-04b1f7610710989f4", "subnet-0c9056c917d94768e"]
  }
}